# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
---
name: Environments Test (OpenAI)

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

env:
  OPENAI_API_KEY: ${{ secrets.openai_api_key }}
  OPENAI_API_TYPE: openai

jobs:
  environment-test-openai:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.11' ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check environment variables are set
        run: |
          if [ -z "$OPENAI_API_KEY" ]; then
            echo "OPENAI_API_KEY environment variable has been set"
            exit 0
          else
            echo "OPENAI_API_KEY environment variable is not set"
            exit 1
          fi
      - name: Install dependencies
        run: |
          sudo apt-get install python3-opengl xvfb
          pip install -e '.[all]'
      - name: Install dependencies
        run: |
          sudo apt-get install python3-opengl xvfb
          pip install -e '.[all]'
      - name: Umshini Environments Test
        run: |
          pytest -v -n auto tests/unit/test_umshini_environments.py
      - name: Regular Environments Test
        run: |
          pytest -v -n auto tests
